### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by Skullians** [TheBjoel2/Slime-Chunk-Finder#2]
Heya,

Is there a chance for ARM Support?
When using the linux version I get "Error: Unsupported Syscall 0x1B3h (435)".
Assuming this is an issue with ARM.

**Comment by TheBjoel2** [comment]
Yeah, it's not a big problem to compile it for ARM. However, I'm currently
quite busy, so I will be able to do so only in about a week. If you need
this program to work on ARM right this moment, your only option is to
compile it yourself. But if you're ok with waiting a bit, I'll do it for
you.

пн, 20 мая 2024 г., 22:23 Skullian ***@***.***>:

**Comment by TheBjoel2** [comment]
@Skullians I uploaded an Aarch64 executable to the [release page](https://github.com/TheBjoel2/Slime-Chunk-Finder/releases). This program was never tested on ARM architecture. Although I'm very sure that it will work, there's still a chance that it won't. If you have any problems with running this binary on ARM, let me know.

**Comment by Skullians** [comment]
It works, thankyou so much!
